---
version: "3.8" 

services:
  web:
    image: devopspracticetogether/springbootapp:latest
    ports:
      - "80:8080"
    networks:
      - my_net

  container:
    image: nginx:latest
    ports: 
      - "81:80"
    networks:
      - my_net

networks:
  my_net:
